### PR TITLE
fix only register icon store if not already present

### PR DESCRIPTION
**Pull request by fabiankaegy**
### Description of the Change

Fix only register icon store if it isn't already registered

Closes #252 

### Changelog Entry

> Fixed - only register icon store if it isn't already registered

### Credits

Props @fabiankaegy @av3nger 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by av3nger** [comment]
@fabiankaegy, how do I test this? I tried building and copying over the `dist` files to the project `node_modules` folder, but then the project is not being built. I tried replacing the whole package, also issues with building

**Comment by fabiankaegy** [comment]
@av3nger In order to make it easier for you to test this in your actual project you can test it by installing this alpha version:

https://www.npmjs.com/package/@10up/block-components/v/1.16.3-testing.0

**Comment by fabiankaegy** [comment]
@av3nger In order to make it easier to test I released a testing version to NPM. See https://github.com/10up/block-components/pull/253#issuecomment-1695519422

**Comment by av3nger** [comment]
This fixes the issue. Thank you!

**Pull request merged**
