### PR TITLE
Use switch/case in Link

### PR DESCRIPTION
**Pull request by szepeviktor**
This is code improvement "only".

1. This change is so obvious
2. It was so much joy to send this PR

### Changelog Entry

Changed - Use switch/case in Link

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by fabiankaegy** [comment]
On general I would agree. However nested switch statements do get somewhat confusing. So closing this for now

**Comment by szepeviktor** [comment]
Yes. But I do not support those users/developers for whom it is somewhat confusing.

**Comment by szepeviktor** [comment]
> I do not support

Meaning I do not allow them to influence my work.
Otherwise I would have to write 👶🏻 baby code.
But I have to admit: in the WordPress ecosystem you don't really meet software engineers.
The WordPress ecosystem is frustrating for engineers as you are unable to fly, just flap your wings and run as fast as you can.

**Comment by fabiankaegy** [comment]
Hi @szepeviktor 👋 

I want to remind you that this project has a [Code of Conduct](https://github.com/10up/block-components/blob/develop/CODE_OF_CONDUCT.md). I have hidden your previous replies because they are not following those rules. 

If you have constructive criticism/reasons why you think my decision to close your PR here you are more than welcome to share those to try and change my mind.

Thank you in advance!

**Comment by szepeviktor** [comment]
> I have hidden your previous replies

You are right Fabian. Telling those facts was really abusive.

**Pull request closed without merging**
