### PR TITLE
Check if query exists before assign (React 18 useEffect issue)

### PR DESCRIPTION
**Pull request by s3rgiosan**
### Description of the Change

I discovered that the <ContentSearch> component is not functioning properly with WordPress 6.2, and I suspect that this is due to the shipment of React 18 (see [this](https://make.wordpress.org/core/2023/03/07/upgrading-to-react-18-and-common-pitfalls-of-concurrent-mode/), [this](https://github.com/facebook/react/issues/24502#issuecomment-1118846544), and [this](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)). When a user types a post title quickly, the component breaks and an error is displayed in the browser's console. 

Screenshot 2023-04-05 at 22 42 32

To address this issue, I have added a check that verifies if the query exists before assigning the results.

### Changelog Entry

> Fixed - Ensure that the search query exists before assigning the results

### Credits

Props @s3rgiosan 

### Checklist:

- [X] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by s3rgiosan** [comment]
@fabiankaegy @Antonio-Laguna Can we get this reviewed and merged ASAP? We have at least two clients that currently are unable to use the `ContentPicker` and `ContentSearch` components because the block breaks as soon as they start typing.
This started to happen since the WP 6.2 update.

**Comment by Antonio-Laguna** [comment]
@s3rgiosan thanks for digging into this and also for providing such a detailed summary!

Looking into this I'm not sure this is the best solution though I'm not sure what the solution is right now. The problem I see with this approach is that API Calls results are not saved. If they don't exist they don't get saved. 

Perhaps it would be safer to initialize the object if it didn't exist and then save it initialized and with data in it?

I don't think there's a need to handle the queries at the state level since there are 5 different places in which `searchQueries` gets updated but I think this is beyond the point at this stage

**Comment by s3rgiosan** [comment]
@Antonio-Laguna thank you for your feedback. I also wasn't totally convinced that it was the best solution, but I ran out of ideas 😆  I've pushed a new update that initializes the query object if it doesn't exist. Can you check?

**Comment by Antonio-Laguna** [comment]
@s3rgiosan that makes me feel better :) 

It looks good to me!

**Review by Antonio-Laguna — APPROVED** [review]

**Review by fabiankaegy — APPROVED** [review]
Also looks great to me :)

**Comment by kkoppenhaver** [comment]
@fabiankaegy @s3rgiosan Thank you for this! We were running into this issue as part of a client launch and this fix saved a couple of our blocks 🎉

**Pull request merged**
