### PR TITLE
Feature: IconPicker TypeScript Conversion

### PR DESCRIPTION
**Pull request by Antonio-Laguna**
### Description of the Change

This migrates the IconPicker to TypeScript and also removes `defaultProps` from it.

Relates to #295 and #314 

### Changelog Entry

> Changed - Moved `IconPicker` to TypeScript

### Checklist:

- [X] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
@fabiankaegy even though tests are passing I see a lot of things on the Cypress run. While there are things that look unrelated, the related ones are odd. I based the code on what was there but those type checking might be coming from WP code or something (see `dashicons` mention)

**Comment by fabiankaegy** [comment]
@Antonio-Laguna yeah currently the `npm run build` command spits out thousands of errors because the types are still very rough and incomplete.

I will review this in a bit :) Thanks for your help <3

**Comment by fabiankaegy** [comment]
@Antonio-Laguna testing this locally I am seeing the following error when trying to add `className` to the `<InlineIconPicker`

CleanShot 2024-05-15 at 11 28 46@2x

https://github.com/10up/block-components/blob/da1cb5f10f7baf3244e24290c546396ff5e8b5b9/example/src/blocks/icon-picker-example/edit.js#L43

**Comment by Antonio-Laguna** [comment]
@fabiankaegy solved :)

**Review by fabiankaegy — APPROVED** [review]
This looks great :) Thanks!

**Pull request merged**
